### ISSUE TITLE
Add Material for FOSSASIA 2016

### ISSUE THREAD

**Issue by aktech** [aktech/sympy-tutorial#19]
TODO
- [x] Update Tutorial website http://iamit.in/sympy-tutorial/
- [x] Update README
- [x] Create new slides
- [x] Update links
- [x] Add TODO

**Comment by aktech** [comment]
@leosartaj @gxyd @shivamvats

**Comment by sumith1896** [comment]
If anyone could, we should have a script that automatically updates author in slides as well as the conference name in the sphinx tutorial. One solution forever :smile:

**Comment by aktech** [comment]
Yeah! :+1:
